---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: code-password
  namespace: code
spec:
  encryptedData:
    password: AgBZna2/lax/DZaVUmVhvHMyeEVntjvlDVrXyTTWILd4tzFpGW4Z7bdvUEp+fvyqYkKaU34n2SzdF6YZwP9MafbVPr3fNXZ74E3/LkL5S/P+/MJfTW6sojMlmrN4NK43acrsXO5xOfiZtaoJzP8GaPOmQZGfM1D0h0+NT9qTuNc9mWmafmdmvSlB7l4EKQxzA2N5AfXr3E3n67vvhQvDsngWKsb8xAYUr5Egig71P6YvkmCWqpzGOM3XnAy0ZZygGO+Q0WetskysECvvLqkf2FFkC7XGJCrFnnUW2bBgsUG3Gpjfq+7wdvgezb32YOWWNqLv/HOhH3+vToEHI4RRriOzmn+KIFefEpAtoornLK9Q6qoeRsWO+SKRSZKdmzxKATmMOdi4H/ZDU9bcJX6H4Njh9n12t26lCs4Ov1ndqKW7pih8GkQrJBQe/2cCt9kGDywdBIa6Vr4bQ9rVSpza2FTprZiFx/TwuMCOhueuAItEO2rHR7V+oL4hGcNqzo8Wo7bj47ushjQFvDtBMgh+dQkxd0n3IGHGTU/csbdiTBC9rqxQ677iDDh7gCzfOcogixBt+jKDPvUaT0Z3k1NAlDI9NvwEu/C3axEU9Ov+317Q0QKR1G8LAy5tAgWVyrObzYtTCVBJz2FZxb+l5n7mgGKTCbwUTNrE4KiblqTb/XCT6RdKRTPxe3qxdqPW+4037Vgojau6zcI+5JyBW0OnJIq0VIyjUJp5mRFO53QQnUMxlQ==
  template:
    metadata:
      creationTimestamp: null
      name: code-password
      namespace: code
