---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: code-claim
  namespace: code
spec:
  storageClassName: freenas-nfs-csi
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi