---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-n8n-claim
  namespace: n8n
spec:
  storageClassName: freenas-nfs-csi
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi