---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: quickshare-credentials
  namespace: quickshare
spec:
  encryptedData:
    password: AgBw963UKFluX/aGfO9d05BL+3x9W1v9VWYg7gGm6D2zRpcV1wZR9TxKWs6RxrClwuRWLgg0bjSZIbZGSZWDlogHk46lVrpxNcmiko6wAn4BWNorpqsaXQvoiVYbTDWUZsX5rSXAnZuXjPLPPKYsnEpbYr8vObnmMAgBtxI6sNFmZUhERBGtV8hEscfe82W3gzmvU98CGS365akvLJYXhJClvl5R7zeSgXGh84LqUYwh/y6kqiqO5+epRXpbEk5QwiMe71en/l4KZGmAMumdkeq0BB3h6o85qmSO07a6Bt0cJsdzp8xJe7EhdopIyWjsOBTvSFcOBWMIp02i9XiD14EX7CjEIEWwiaKM5JFBmcpCNKzNLYn2gsXElr9OryLHTKyOq3oJ/sa+vVJx5ogywq1Sjogf8/yQAKagKn1qBbEVS1fIuKAjkQP1HNOMjE6EdqAu1RLjP5pigLD24ErV6DsMbNusOpZcbAiRPXRHCUm9IecrBeLG9m72LvQEHR+44eM1H/F2qIE/QPICx1RI3ltDeKwZZ96E6IODbVdGsTMw9zP+gcpLO1mbyxEBDL6yl98fmwvCtvAEMaEM33REWiGaEJMngl8ycqTUr/AU9g7omEH9O6cSYxEBERbmlanNYGcO01If9HxHOomqw+J3Li3XCMGcYlK1Wx7rqxwiJVw0hkWODKaacqty3ErWpzYiiFzANi9G529SLmvKoH6+8WrrsTmMsHLyUWA2ggzFszzOvQ==
    username: AgBtzMFduLzHVLTrw7tvcOHumGUDhF2HfMizWt6hU+FbpHZnjmr4CTIPgsHkkA7OO/3qcNghXF+dLUp27p2fVpcXKcniYrDOsIVZhZkh63wKN9R+AYC8Dqeg+GSmqm4zVY/QIKG5CewDofyYWN8qYnUjcGSQOFosNm+Xsus9lya7x08yqpOHgXLw+4agb+y2P6zxZviuI/J3AaQNF21tKo2KKVjsE3o9xG5r3mgj0+62HSVEIhmM8LN3ecED6pYk7ZabRDmmz3uqFkWZFeXhBbt6DoJ/fPNKvjSS4cxBLQxpELCkBjktXsAmtpLkJ01gSY7is/uXDwyLNefZ0SZbn/INzar8QJA3yDdmzrFkZengcF5y2W3oy8pAbe/JtZXgNF4R8UaoKfR+gp7Hs/Vuoynka7nucFQChPXGGGbVtNCjsdAxHkUXqDmEC2IxNnn+LxXIpthqU4AYkwLam5Vp2D3P42Jx4DAjP0AYDfkX2T+c7nJD7nRQMY04KWYNBIzhF8WLLP2tEc47o+bxTb3Kgn/98kl/9HjGztZNXwBvafnwvilqiND8SnNKntL8o/edKvGVZvBCggtHYXOau1lVJ8YMArcdgne/yeSSQHd7S7PjVzdWEX08XGK+j+mdIEO4rINCfH70ntDVbjQ/v2dHGt8/j9nVZRxiioKG2hNVUx2M+moOYdjCZNk8pRbduGy2Y1WBqBUGuA==
  template:
    metadata:
      creationTimestamp: null
      name: quickshare-credentials
      namespace: quickshare
    type: Opaque
