# PersistentVolumeClaim for application configuration
# Stores app config files (settings, etc.)
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: quickshare-claim
  namespace: quickshare
spec:
  storageClassName: freenas-nfs-csi
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi