---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: smb.csi.k8s.io
  name: pv-music
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: smb-reader
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
  csi:
    driver: smb.csi.k8s.io
    readOnly: true
    # volumeHandle format: {smb-server-address}#{sub-dir-name}#{share-name}
    # make sure this value is unique for every share in the cluster
    volumeHandle: Music
    volumeAttributes:
      source: "//192.168.1.52/Music" # Change this to your SMB IP and share name
    nodeStageSecretRef:
      name: smbcreds-reader
      namespace: kube-system
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: navidrome-claim-music
  namespace: navidrome
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: pv-music
  storageClassName: smb-reader

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: navidrome-claim-data
  namespace: navidrome
spec:
  storageClassName: freenas-nfs-csi
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 100Mi
