apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: speedtest-tracker
  namespace: speedtest
spec:
  storageClassName: freenas-nfs-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi