apiVersion: v1
kind: Service
metadata:
  labels:
    app: sqlitebrowser
  name: sqlitebrowser-service
  namespace: sqlitebrowser
spec:
  ports:
    - name: "http"
      port: 80
      targetPort: 3000
    - name: "3001"
      port: 3001
      targetPort: 3001
  selector:
    app: sqlitebrowser
