apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sqlitebrowser-config
  namespace: sqlitebrowser
spec:
  storageClassName: freenas-nfs-csi
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
